debug: true

spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: eventhubckpt
          container-name: eventhubckpt
      redis:
        name: jayredis
        resource:
          resource-group: sandbox-rg
      profile:
        subscription-id:
  application:
    name: sca4-sample

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9090
  endpoint:
    health:
      show-details: always